export const ADD_PRESET = 'ADD_PRESET';
export const SET_PRESET = 'SET_PRESET';
export const DELETE_PRESET = 'DELETE_PRESET';
export const SET_PRESET_PROGRESS_NAME = 'SET_PRESET_PROGRESS_NAME';
export const SET_PRESET_PROGRESS_SERVER = 'SET_PRESET_PROGRESS_SERVER';
export const SET_PRESET_PROGRESS_INPUT = 'SET_PRESET_PROGRESS_INPUT';
export const SET_PRESET_PROGRESS_DECODER = 'SET_PRESET_PROGRESS_DECODER';
export const SET_PRESET_PROGRESS_OUTPUT = 'SET_PRESET_PROGRESS_OUTPUT';
export const COMMIT_PRESET_PROGRESS = 'COMMIT_PRESET_PROGRESS';
export const FLUSH_PRESET_PROGRESS = 'FLUSH_PRESET_PROGRESS';


